site_name: WAVLINK Docs
site_description: Documentation for WAVLINK Router Productions
site_author: WAVLINK

nav: 
  - Home: index.md
  - User Guide: 
    - Overview: user_guide/index.md
    - AX6000: 
      - AX6000: user_guide/ax6000/index.md
      - WS-WN536AX6-A: user_guide/ax6000/wn536ax6-a/index.md
    
    - AX3000:
      - AX3000: user_guide/ax3000/index.md
      - WS-WN551X3-A: user_guide/wn551x3-a/index.md
      - WS-WN588HX3-B: user_guide/wn588hx3-b/index.md
      - WS-WN573HX3-A: user_guide/wn573hx3-a/index.md
      - WS-WN583X1-A: user_guide/wn583x1-a/index.md
      - WS-WN586X3-B: user_guide/wn586x3-b/index.md
      - WS-WN586X3-A: user_guide/wn586x3-a/index.md
      - WS-WN573HP3-A: user_guide/wn573hp3-a/index.md
      - WS-WN531AX3-A: user_guide/wn531ax3-a/index.md
      - WS-WN531MX3-A: user_guide/wn531mx3-a/index.md
    - AC1200:
      - AC1200: user_guide/ac1200/index.md
    - N3000:
      - N3000: user_guide/n3000/index.md
  - FAQ: FAQ/index.md
  - Tutorials: tutorials/index.md
  - Interface Guide: interface_guide/index.md
  - Video Library: video_library/index.md
  - Community: community/index.md

theme: 
  name: material
  logo: images/logo1.png
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  favicon: images/logo-icon.png
 
extra_css:
  - stylesheets/extra.css

