site_name: WAVLINK Docs
site_description: Documentation for WAVLINK Router Productions
site_author: WAVLINK
copyright: Copyright 2023 WAVLINK Technology Co., Ltd.

nav: 
  - Welcom: index.md
  - Products: 
    - Overview: Products/index.md
    - AX6000: 
      - AX6000: Products/ax6000/index.md
      - WS-WN536AX6-A: Products/ax6000/wn536ax6-a/index.md
      - WS-WN592AX6-A: Products/ax6000/wn592ax6-a/index.md
    - AX3000:
      - AX3000: Products/ax3000/index.md
      - WS-591AX3-A: Products/ax3000/wn591ax3-a/index.md
      - WS-WN573HX3-A: Products/ax3000/wn573hx3-a/index.md
      - WS-WN583AX3-A: Products/ax3000/wn583ax3-a/index.md
      - WS-WN586X3-A: Products/ax3000/wn586x3-a/index.md
      - WS-WN573HP3-A: Products/ax3000/wn573hp3-a/index.md
      - WS-WN531AX3-A: Products/ax3000/wn531ax3-a/index.md
      - WS-WNF100X3NR-A: Products/ax3000/wnf100x3nr-a/index.md
    - AC1200:
      - AC1200: Products/ac1200/index.md
    - N3000:
      - N3000: Products/n3000/index.md
  - FAQ: FAQ/index.md
  - Tutorials: tutorials/index.md
  - Feature Guide: feature_guide/index.md
  - Video Library: video_library/index.md
  - Community: community/index.md

theme: 
  name: material
  logo: images/logo1.png
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  favicon: images/logo-icon.png
 
extra_css:
  - stylesheets/extra.css

